version: '2'
services:
  docker-registry:
    image: registry:latest
    ports:
      - '5555:5000'
    restart: always

  docker:
    image: docker:stable-dind
    privileged: true
    links:
      - docker-registry:reg
    command: --insecure-registry reg:5000
    restart: always

  invoice-mysql:
    build: ../InvoiceDB
    image: invoicemysql
    volumes:
      - ./data/mysql:/data/db
    restart: always

  invoce-app:
    build: ../InvoiceApp
    image: invoiceapp
    ports:
      - '10000:10000'
    links:
      - invoice-mysql:mysql
    restart: always

  invoice-web:
    build: ../InvoiceWeb/
    image: invoceweb
    ports:
      - '10001:10001'
    environment:
      - NODE_ENV=production
    restart: always

  invoice-ci:
    build: ../InvoiceCI/
    image: invoceci
    ports:
      - '443:443'
    links:
      - invoice-app:invoiceapp
    environment:
      - NODE_ENV=production
    restart: always
